In [2]:
import torch

## Tensor

In [4]:
x = torch.empty(5, 3)
x

tensor([[1.0102e-38, 8.4490e-39, 9.6429e-39],
        [8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 1.0653e-38]])

In [8]:
x = torch.rand(5, 3)
x

tensor([[0.7040, 0.1988, 0.6796],
        [0.4300, 0.7827, 0.6279],
        [0.1349, 0.7978, 0.2615],
        [0.2353, 0.3220, 0.7499],
        [0.2013, 0.9481, 0.5570]])

In [10]:
x = torch.zeros(5, 3, dtype=torch.float)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [12]:
x = x.new_ones(5, 3)  # reuse properties of the input tensor, e.g. dtype
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
x = torch.randn_like(x, dtype=torch.float)  # has the same size
print(x.size())  # 支持tuple的操作
x

torch.Size([5, 3])


tensor([[ 0.2125, -0.2498,  2.2110],
        [ 0.3578, -0.3959, -0.2382],
        [-0.0578, -1.8822,  0.1953],
        [-0.5789,  0.1653,  1.4361],
        [-0.5079,  0.4445, -0.8825]])

## Operations

In [17]:
y = torch.rand(5, 3)
y

tensor([[0.7791, 0.2957, 0.4316],
        [0.1900, 0.0661, 0.0131],
        [0.2625, 0.4346, 0.5725],
        [0.7153, 0.9921, 0.1835],
        [0.3431, 0.1381, 0.3642]])

In [18]:
x + y

tensor([[ 0.9915,  0.0459,  2.6426],
        [ 0.5478, -0.3298, -0.2251],
        [ 0.2046, -1.4476,  0.7678],
        [ 0.1364,  1.1574,  1.6196],
        [-0.1649,  0.5826, -0.5183]])

In [19]:
torch.add(x, y)

tensor([[ 0.9915,  0.0459,  2.6426],
        [ 0.5478, -0.3298, -0.2251],
        [ 0.2046, -1.4476,  0.7678],
        [ 0.1364,  1.1574,  1.6196],
        [-0.1649,  0.5826, -0.5183]])

In [20]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 0.9915,  0.0459,  2.6426],
        [ 0.5478, -0.3298, -0.2251],
        [ 0.2046, -1.4476,  0.7678],
        [ 0.1364,  1.1574,  1.6196],
        [-0.1649,  0.5826, -0.5183]])

In [21]:
y.add_(x)

tensor([[ 0.9915,  0.0459,  2.6426],
        [ 0.5478, -0.3298, -0.2251],
        [ 0.2046, -1.4476,  0.7678],
        [ 0.1364,  1.1574,  1.6196],
        [-0.1649,  0.5826, -0.5183]])

In [22]:
x

tensor([[ 0.2125, -0.2498,  2.2110],
        [ 0.3578, -0.3959, -0.2382],
        [-0.0578, -1.8822,  0.1953],
        [-0.5789,  0.1653,  1.4361],
        [-0.5079,  0.4445, -0.8825]])

In [25]:
x[:, 1]

tensor([-0.2498, -0.3959, -1.8822,  0.1653,  0.4445])

In [30]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [34]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0100])
-1.009965419769287


In [39]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [41]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [42]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [43]:
import numpy as np

In [47]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [51]:
x = torch.ones(5)
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([2., 2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [52]:
x.to?