`autograd`：a define-by-run framework, 即your backprop is defined by how your code is run, and that every single iteration is different.

## Tensor

In [2]:
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [16]:
z = y * y * 4
out = z.mean()
z, out

(tensor([[36., 36.],
         [36., 36.]], grad_fn=<MulBackward0>),
 tensor(36., grad_fn=<MeanBackward0>))

In [22]:
a = torch.randn(2, 3)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)
b

False
True


tensor(43.3151, grad_fn=<SumBackward0>)

## Gradients

In [24]:
out.backward()

In [26]:
x.grad  # gradents of d(out)/dx

tensor([[6., 6.],
        [6., 6.]])

In [27]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [43]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
y

tensor([  540.9234, -1018.9073,    93.1151], grad_fn=<MulBackward0>)

In [36]:
torch.norm?

In [44]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float)
y.backward(v)

In [45]:
x.grad

tensor([ 204.8000, 2048.0000,    2.0480])

In [50]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
